version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: bdtea
    volumes:
      - ./database/bdtea.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tea
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    networks:
      - tea-network
    restart: always
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s

  back-end:
    build: 
      context: back
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - tea-network
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: bdtea
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_NAME: tea
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 8800
  
  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - tea-network
    depends_on:
       - back-end
       - front-end

  front-end:
    build: 
      context: front
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - tea-network
    volumes: 
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm run dev

networks:
  tea-network:
    driver: bridge